site_name: ARG Guidelines 
site_url: https://github.com/snt-arg/new_guidelines
theme:
  name: material
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
